dist: xenial
android:
  components:
    - build-tools-28.0.3
jdk: oraclejdk8
addons:
  apt:
    packages:
    - ant
before_install:
 - pushd com.ibm.wala.memsat
 - ant getJars
 - popd
 - git clone --depth=50 https://github.com/wala/WALA /tmp/WALA
install:
 - pushd /tmp/WALA
 - mvn clean install -B -q -DskipTests
 - popd
script:
 - mvn clean install -B -q
sudo: false
cache:
  directories:
    - $HOME/.m2
